FROM node:18-alpine

WORKDIR /app

# Installer nodemon globalement
RUN npm install -g nodemon

# Copier les fichiers de dépendances
COPY package*.json ./
COPY prisma ./prisma/

# Installer toutes les dépendances (dev + prod)
RUN npm install

# Générer le client Prisma
RUN npx prisma generate

# Exposer le port
EXPOSE 5000

# Commande par défaut (sera surchargée par docker-compose)
CMD ["npm", "run", "dev"]